'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faArrowLeft, faCalendarDays, faCheck, faClock, faCopy, faLocationDot, faMinus, faPlus, faShareNodes, faTicket, faTriangleExclamation, faUsers } from '@fortawesome/free-solid-svg-icons';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { SocialFloat } from '@/components/SocialFloat';
import { EventCard, type EventCardData } from '@/components/EventCard';
import { PublicCompaniesCarousel } from '@/components/PublicCompaniesCarousel';
import { useCart } from '@/components/providers/CartProvider';
import { ticketService } from '@/services/public/ticketService';
import { publicEventService } from '@/services/public/publicEventService';
import type { PublicEvent } from '@/services/public/types';
import { formatCurrency, formatEventDate, formatEventTime, formatPrice, formatShortDate } from '@/utils/publicFormatters';

export function EventDetailsPage({ slug }: { slug: string }) {
  const [event, setEvent] = useState<PublicEvent | null>(null); const [related, setRelated] = useState<PublicEvent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [quantity, setQuantity] = useState(0); const [feedback, setFeedback] = useState(''); const cart = useCart();
  useEffect(() => { let active = true; Promise.all([ticketService.getEvent(slug), publicEventService.list()]).then(([item, list]) => { if (!active) return; setEvent(item); setRelated(list.filter((other) => other.id !== item.id && (other.type === item.type || other.city === item.city)).slice(0, 3)); }).catch((reason) => active && setError(reason instanceof Error ? reason.message : 'Evento não encontrado.')).finally(() => active && setLoading(false)); return () => { active = false; }; }, [slug]);
  if (loading) return <PageState text="Carregando detalhes do evento..."/>;
  if (error || !event) return <PageState text={error || 'Evento não encontrado.'} error/>;
  const currentEvent = event;
  const unavailable = event.status !== 'ATIVO' || event.soldOut || (event.type !== 'CURSO' && event.salesEndAt ? new Date(event.salesEndAt) < new Date() : false); const max = unavailable ? 0 : (event.available ?? Number.MAX_SAFE_INTEGER); const short = formatShortDate(event.date); const parsed = parseDescription(event.description); const address = [event.place, event.city].filter(Boolean).join(' • ');
  function addToCart() { if (!event || quantity < 1 || unavailable) return; cart.add(event, quantity); setFeedback('Ingresso adicionado ao carrinho.'); }
  async function share() { const payload = { title: currentEvent.title, text: `${formatEventDate(currentEvent.date)} • ${address}`, url: window.location.href }; try { if (navigator.share) await navigator.share(payload); else { await navigator.clipboard.writeText(payload.url); setFeedback('Link copiado.'); } } catch { /* Native share cancelled. */ } }
  async function copyAddress() { await navigator.clipboard.writeText(address); setFeedback('Endereço copiado.'); }
  return <main className="min-h-screen overflow-x-hidden bg-[#030705] text-white"><Header active="bilheteria"/><SocialFloat/><div className="relative px-4 pb-20 pt-32 md:px-6"><div className="pointer-events-none absolute inset-x-0 top-0 h-[650px] overflow-hidden"><Image src={event.image ?? '/assets/bg-hero.png'} alt="" fill priority sizes="100vw" className="object-cover opacity-20 blur-2xl"/><div className="absolute inset-0 bg-gradient-to-b from-black/80 via-[#030705]/90 to-[#030705]"/></div><div className="relative mx-auto max-w-[1560px]"><Link href="/bilheteria" className="inline-flex items-center rounded-full border border-white/15 bg-black/30 px-5 py-3 text-sm font-black hover:border-gaucho-gold"><FontAwesomeIcon icon={faArrowLeft} className="mr-2"/>Voltar para a Bilheteria</Link>
    <section className="mt-6 overflow-hidden rounded-[28px] border border-gaucho-gold/20 bg-[#07100b]/95 shadow-2xl"><div className="grid lg:grid-cols-[40%_60%]"><EventPoster event={event}/><div className="p-5 md:p-8 lg:p-10"><h1 className="font-display text-4xl font-black leading-tight md:text-5xl">{event.title}</h1><p className="mt-3 text-sm font-black uppercase tracking-[.2em] text-gaucho-gold">Informações do evento</p><Summary event={event}/><Location address={address} onCopy={copyAddress}/><div className="mt-5 grid gap-5 xl:grid-cols-2">{parsed.important.length > 0 && <ListCard title="INFORMAÇÕES IMPORTANTES" items={parsed.important} positive/>}{event.type !== 'CURSO' && parsed.rules.length > 0 && <ListCard title="REGRAS DO EVENTO" items={parsed.rules}/>}</div></div></div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="rounded-3xl border border-white/10 bg-[#07100b] p-5 md:p-8"><h2 className="font-display text-3xl font-black">Escolha seu ingresso</h2><div className="mt-6 grid items-center gap-4 rounded-2xl border border-white/10 bg-white/5 p-5 sm:grid-cols-[1fr_auto]"><div><span className="text-xs font-black text-gaucho-gold">{event.type}</span><h3 className="mt-1 text-xl font-black">Ingresso • {event.title}</h3><p className="mt-2 text-sm text-white/55">{unavailable ? 'Vendas encerradas ou indisponíveis' : event.startingPrice ? formatCurrency(event.startingPrice) : 'GRATUITO'}</p></div><div className="flex items-center gap-3"><button aria-label="Diminuir quantidade" onClick={() => setQuantity(Math.max(0, quantity - 1))} className="h-11 w-11 rounded-lg border border-white/20"><FontAwesomeIcon icon={faMinus}/></button><b className="w-8 text-center text-xl">{quantity}</b><button aria-label="Aumentar quantidade" disabled={quantity >= max} onClick={() => setQuantity(Math.min(max, quantity + 1))} className="h-11 w-11 rounded-lg border border-white/20 disabled:opacity-30"><FontAwesomeIcon icon={faPlus}/></button></div></div></div><aside className="h-fit rounded-3xl border border-gaucho-gold/20 bg-[#07100b] p-6 lg:sticky lg:top-28"><h2 className="text-xl font-black">Resumo da compra</h2><p className="mt-5 flex justify-between"><span>Quantidade</span><b>{quantity}</b></p><p className="mt-3 flex justify-between"><span>Total</span><b className="text-gaucho-gold">{event.startingPrice ? formatCurrency(event.startingPrice * quantity) : 'Gratuito'}</b></p><button disabled={!quantity || unavailable} onClick={addToCart} className="mt-6 min-h-16 w-full rounded-2xl bg-gaucho-red px-4 font-black disabled:opacity-40">ADICIONAR AO CARRINHO</button><button onClick={share} className="mt-3 min-h-12 w-full rounded-xl border border-gaucho-gold/35 font-black"><FontAwesomeIcon icon={faShareNodes} className="mr-2"/>COMPARTILHAR EVENTO</button>{feedback && <p className="mt-3 text-center text-xs text-green-400">{feedback}</p>}</aside></section>
    {parsed.about.length > 0 && <section className="mt-8 rounded-3xl border border-white/10 bg-[#07100b] p-6 md:p-9"><h2 className="font-display text-3xl font-black">Sobre o evento</h2><div className="mt-5 max-w-4xl space-y-4 leading-8 text-white/70">{parsed.about.map((text) => <p key={text}>{text}</p>)}</div></section>}
    {related.length > 0 && <section className="mt-12"><h2 className="font-display text-3xl font-black">Eventos relacionados</h2><div className="mt-6 flex flex-wrap justify-center gap-5">{related.map((item) => <div key={item.id} className="w-[min(88vw,340px)]"><EventCard event={toCard(item)} detailsHref={`/bilheteria/eventos/${item.slug ?? item.id}`} buyHref={`/bilheteria/eventos/${item.slug ?? item.id}`}/></div>)}</div></section>}
    <section className="mt-12"><h2 className="text-center font-display text-3xl font-black">Nossos apoiadores</h2><div className="mt-6"><PublicCompaniesCarousel/></div></section></div></div><Footer/></main>;
}
function EventPoster({ event }: { event: PublicEvent }) { return <div className="relative min-h-[460px] bg-black lg:min-h-[720px]"><Image src={event.image ?? '/assets/bg-hero.png'} alt={`Banner oficial de ${event.title}`} fill priority sizes="(max-width:1024px) 100vw, 620px" className="object-contain"/><span className="absolute left-5 top-5 rounded-full bg-gaucho-red px-4 py-2 text-xs font-black">{event.type ?? 'EVENTO'}</span></div>; }
function Summary({ event }: { event: PublicEvent }) { const cards = [{icon:faCalendarDays,label:'DATA',value:formatEventDate(event.date)},{icon:faClock,label:'HORÁRIO',value:formatEventTime(event.date)},{icon:faTicket,label:'VALOR',value:formatPrice(event.startingPrice,event.type==='CURSO'?'Taxa':'Entrada')},{icon:faUsers,label:'DISPONIBILIDADE',value:event.soldOut?'Esgotado':event.available==null?'Vagas limitadas':`${event.available} disponíveis`}]; return <div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map((card)=><div key={card.label} className="rounded-2xl border border-white/10 bg-white/5 p-4"><FontAwesomeIcon icon={card.icon} className="text-gaucho-gold"/><span className="ml-2 text-[10px] font-black text-white/45">{card.label}</span><p className="mt-2 text-sm font-black">{card.value}</p></div>)}</div>; }
function Location({ address,onCopy }:{address:string;onCopy:()=>void}) { const maps=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`; return <div className="mt-5 rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="text-xs font-black tracking-[.18em] text-gaucho-gold"><FontAwesomeIcon icon={faLocationDot} className="mr-2"/>LOCAL DO EVENTO</h2><p className="mt-3 text-lg font-black">{address||'Local a confirmar'}</p>{address&&<div className="mt-4 flex flex-wrap gap-3"><a href={maps} target="_blank" rel="noopener noreferrer" className="rounded-lg bg-gaucho-gold px-4 py-3 text-xs font-black text-black">VER NO MAPA</a><button onClick={onCopy} className="rounded-lg border border-white/20 px-4 py-3 text-xs font-black"><FontAwesomeIcon icon={faCopy} className="mr-2"/>COPIAR ENDEREÇO</button></div>}</div>; }
function ListCard({title,items,positive=false}:{title:string;items:string[];positive?:boolean}) { return <div className={`rounded-2xl border p-5 ${positive?'border-green-500/25 bg-green-950/20':'border-red-500/25 bg-red-950/20'}`}><h2 className={`text-xs font-black tracking-[.16em] ${positive?'text-green-400':'text-red-400'}`}>{title}</h2><ul className="mt-4 space-y-3 text-sm text-white/75">{items.map((item)=><li key={item}><FontAwesomeIcon icon={positive?faCheck:faTriangleExclamation} className={`mr-2 ${positive?'text-green-400':'text-red-400'}`}/>{item}</li>)}</ul></div>; }
function parseDescription(value?:string){const parts=(value??'').split(/\n|;/).map(x=>x.trim()).filter(Boolean);const rules=parts.filter(x=>/não |proibid|menor|regata|chinelo|drogas|fumar/i.test(x)&&!/se beber/i.test(x));const important=parts.filter(x=>!rules.includes(x)&&/preço|antecip|estacionamento|whatsapp|telefone|venda|internet|wi-fi|reembolso/i.test(x));return{rules,important,about:parts.filter(x=>!rules.includes(x)&&!important.includes(x)&&!/se beber/i.test(x))};}
function toCard(event:PublicEvent):EventCardData{const short=formatShortDate(event.date);return{id:event.id,title:event.title,city:event.city??'',place:event.place??'',date:short.day,month:short.month,time:formatEventTime(event.date),price:event.startingPrice??0,remain:event.available??undefined,image:event.image??'/assets/bg-hero.png',type:event.type??'EVENTO'};}
function PageState({text,error=false}:{text:string;error?:boolean}){return <main className="min-h-screen bg-[#030705] text-white"><Header active="bilheteria"/><div className="mx-auto max-w-3xl px-6 pt-44 text-center"><h1 className={`font-display text-4xl font-black ${error?'text-red-400':''}`}>{text}</h1><Link href="/bilheteria" className="mt-8 inline-block rounded-xl bg-gaucho-red px-6 py-4 font-black">Voltar para a Bilheteria</Link></div></main>;}
