'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { useAuth } from '@/components/providers/AuthProvider';
import { useCart } from '@/components/providers/CartProvider';

export default function CartPage() {
  const cart = useCart(); const { user } = useAuth(); const router = useRouter();
  const estimated = cart.items.reduce((sum, item) => sum + (item.snapshot.startingPrice ?? 0) * item.quantity, 0);
  const checkout = () => router.push(user ? '/checkout' : '/login?returnTo=/checkout');
  return <main className="min-h-screen bg-gaucho-cream text-black"><Header active="bilheteria" /><section className="mx-auto max-w-5xl px-6 pb-24 pt-36"><h1 className="font-display text-5xl font-black">Seu carrinho</h1>{cart.items.length === 0 ? <div className="mt-10 rounded-2xl bg-white p-10 text-center shadow-xl"><h2 className="text-2xl font-black">Seu carrinho está vazio</h2><p className="mt-2 text-black/60">Explore nossos eventos, bailes e cursos e escolha sua próxima experiência.</p><Link href="/bilheteria" className="mt-6 inline-block rounded-lg bg-gaucho-red px-7 py-3 font-black text-white">Explorar bilheteria</Link></div> : <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><div className="space-y-4">{cart.items.map((item) => <article key={item.eventId} className="grid grid-cols-[90px_1fr] gap-4 rounded-xl bg-white p-4 shadow-lg"><div className="relative h-24 overflow-hidden rounded-lg bg-black/10">{item.snapshot.image && <Image src={item.snapshot.image} alt={item.snapshot.title} fill className="object-cover" />}</div><div><span className="text-xs font-black text-gaucho-red">{item.snapshot.type}</span><h2 className="text-xl font-black">{item.snapshot.title}</h2><p className="text-sm text-black/55">{item.snapshot.city} • {item.snapshot.place}</p><div className="mt-3 flex items-center gap-3"><button onClick={() => cart.setQuantity(item.eventId, item.quantity - 1)} className="rounded border px-3 py-1">−</button><b>{item.quantity}</b><button onClick={() => cart.setQuantity(item.eventId, item.quantity + 1)} disabled={item.snapshot.type === 'CURSO'} className="rounded border px-3 py-1 disabled:opacity-30">+</button><button onClick={() => cart.remove(item.eventId)} className="ml-auto text-sm font-bold text-red-700">Remover</button></div></div></article>)}</div><aside className="h-fit rounded-xl bg-white p-6 shadow-xl"><h2 className="text-xl font-black">Resumo estimado</h2><p className="mt-5 flex justify-between"><span>Subtotal</span><b>{new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(estimated)}</b></p><p className="mt-2 flex justify-between text-sm text-black/55"><span>Taxas estimadas</span><span>Calculadas no checkout</span></p><p className="mt-5 border-t pt-4 text-xs text-black/55">Preços, disponibilidade e total serão recalculados pelo backend antes da confirmação.</p><button onClick={checkout} className="mt-6 w-full rounded-lg bg-gaucho-red py-4 font-black uppercase text-white">Finalizar compra</button><button onClick={cart.clear} className="mt-3 w-full py-2 text-sm text-black/55">Esvaziar carrinho</button></aside></div>}</section><Footer /></main>;
}
