'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { meService, type CustomerOrder } from '@/services/meService';
import { TicketQrCode } from './TicketQrCode';

export function OrdersList() { const [data, setData] = useState<CustomerOrder[] | null>(null); useEffect(() => { meService.orders().then((r) => setData(r.data)); }, []); if (!data) return <Loading />; if (!data.length) return <Empty title="Você ainda não realizou nenhuma compra" text="Quando você comprar ingressos ou se inscrever em um curso, seus pedidos aparecerão aqui." />; return <div className="space-y-4">{data.map((order) => <Link key={order.id} href={`/minha-conta/pedidos/${order.id}`} className="block rounded-xl bg-white p-5 shadow-lg"><div className="flex justify-between gap-4"><div><b>{order.code}</b><p className="mt-1 text-sm text-black/55">{new Date(order.createdAt).toLocaleDateString('pt-BR')} • {order.statusLabel}</p></div><strong>{new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(order.total)}</strong></div></Link>)}</div>; }
export function TicketsList() { const [data, setData] = useState<Array<Record<string, unknown>> | null>(null); useEffect(() => { meService.tickets().then((r) => setData(r.data)); }, []); if (!data) return <Loading />; if (!data.length) return <Empty title="Você ainda não possui ingressos" text="Seus ingressos pagos e válidos aparecerão aqui." />; return <Cards data={data} kind="ticket" />; }
export function EnrollmentsList() { const [data, setData] = useState<Array<Record<string, unknown>> | null>(null); useEffect(() => { meService.enrollments().then((r) => setData(r.data)); }, []); if (!data) return <Loading />; if (!data.length) return <Empty title="Você ainda não possui inscrições" text="Suas inscrições em cursos aparecerão aqui." />; return <Cards data={data} kind="enrollment" />; }
function Cards({ data, kind }: { data: Array<Record<string, unknown>>; kind: string }) { return <div className="grid gap-4 sm:grid-cols-2">{data.map((item) => { const event = item.evento as Record<string, unknown> | undefined; return <article key={String(item.id)} className="rounded-xl bg-white p-5 shadow-lg"><span className="text-xs font-black text-gaucho-red">{kind === 'ticket' ? 'INGRESSO' : 'INSCRIÇÃO'}</span><h2 className="mt-2 text-xl font-black">{String(event?.nome ?? 'Coração Gaúcho')}</h2><p className="mt-2 text-sm text-black/55">{String(event?.local ?? '')} • {String(event?.cidade ?? '')}</p><p className="mt-4 font-bold">{String(item.statusLabel ?? item.status)}</p>{kind === 'ticket' && <><TicketQrCode value={String(item.qrcode ?? item.id)} /><p className="mt-2 break-all rounded bg-black/5 p-2 text-xs">Código: {String(item.qrcode ?? item.id)}</p></>}</article>; })}</div>; }
function Loading() { return <div className="h-48 animate-pulse rounded-xl bg-black/10" />; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-xl bg-white p-8 text-center shadow-lg"><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-black/60">{text}</p></div>; }
